// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.11.2
// source: internal/grpc/files/file.proto

package files

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DstDir   string `protobuf:"bytes,1,opt,name=dstDir,proto3" json:"dstDir,omitempty"`
	ProjName string `protobuf:"bytes,2,opt,name=projName,proto3" json:"projName,omitempty"`
	Name     string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ProjType int32  `protobuf:"varint,4,opt,name=projType,proto3" json:"projType,omitempty"`
	IfReboot bool   `protobuf:"varint,5,opt,name=ifReboot,proto3" json:"ifReboot,omitempty"`
	Hash     string `protobuf:"bytes,6,opt,name=hash,proto3" json:"hash,omitempty"`
	Filelen  int64  `protobuf:"varint,7,opt,name=filelen,proto3" json:"filelen,omitempty"`
	File     []byte `protobuf:"bytes,8,opt,name=file,proto3" json:"file,omitempty"`
}

func (x *FileReq) Reset() {
	*x = FileReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpc_files_file_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileReq) ProtoMessage() {}

func (x *FileReq) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_files_file_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileReq.ProtoReflect.Descriptor instead.
func (*FileReq) Descriptor() ([]byte, []int) {
	return file_internal_grpc_files_file_proto_rawDescGZIP(), []int{0}
}

func (x *FileReq) GetDstDir() string {
	if x != nil {
		return x.DstDir
	}
	return ""
}

func (x *FileReq) GetProjName() string {
	if x != nil {
		return x.ProjName
	}
	return ""
}

func (x *FileReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileReq) GetProjType() int32 {
	if x != nil {
		return x.ProjType
	}
	return 0
}

func (x *FileReq) GetIfReboot() bool {
	if x != nil {
		return x.IfReboot
	}
	return false
}

func (x *FileReq) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *FileReq) GetFilelen() int64 {
	if x != nil {
		return x.Filelen
	}
	return 0
}

func (x *FileReq) GetFile() []byte {
	if x != nil {
		return x.File
	}
	return nil
}

type FileRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  bool   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *FileRes) Reset() {
	*x = FileRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_grpc_files_file_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRes) ProtoMessage() {}

func (x *FileRes) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_files_file_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRes.ProtoReflect.Descriptor instead.
func (*FileRes) Descriptor() ([]byte, []int) {
	return file_internal_grpc_files_file_proto_rawDescGZIP(), []int{1}
}

func (x *FileRes) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *FileRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_internal_grpc_files_file_proto protoreflect.FileDescriptor

var file_internal_grpc_files_file_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x66, 0x69, 0x6c, 0x65, 0x73, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xcb, 0x01, 0x0a, 0x07, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06,
	0x64, 0x73, 0x74, 0x44, 0x69, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x73,
	0x74, 0x44, 0x69, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x6a, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x6a, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x6a, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x6a, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x69, 0x66, 0x52, 0x65, 0x62, 0x6f, 0x6f, 0x74, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x08, 0x69, 0x66, 0x52, 0x65, 0x62, 0x6f, 0x6f, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x68, 0x61, 0x73, 0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68,
	0x12, 0x18, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x6c, 0x65, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x6c, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x69,
	0x6c, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x22, 0x3b,
	0x0a, 0x07, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x2d, 0x0a, 0x0b, 0x46,
	0x69, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x1e, 0x0a, 0x08, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x12, 0x08, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71,
	0x1a, 0x08, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x42, 0x14, 0x5a, 0x12, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_grpc_files_file_proto_rawDescOnce sync.Once
	file_internal_grpc_files_file_proto_rawDescData = file_internal_grpc_files_file_proto_rawDesc
)

func file_internal_grpc_files_file_proto_rawDescGZIP() []byte {
	file_internal_grpc_files_file_proto_rawDescOnce.Do(func() {
		file_internal_grpc_files_file_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_grpc_files_file_proto_rawDescData)
	})
	return file_internal_grpc_files_file_proto_rawDescData
}

var file_internal_grpc_files_file_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_grpc_files_file_proto_goTypes = []interface{}{
	(*FileReq)(nil), // 0: FileReq
	(*FileRes)(nil), // 1: FileRes
}
var file_internal_grpc_files_file_proto_depIdxs = []int32{
	0, // 0: FileService.Transfer:input_type -> FileReq
	1, // 1: FileService.Transfer:output_type -> FileRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_grpc_files_file_proto_init() }
func file_internal_grpc_files_file_proto_init() {
	if File_internal_grpc_files_file_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_grpc_files_file_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_grpc_files_file_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_grpc_files_file_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_files_file_proto_goTypes,
		DependencyIndexes: file_internal_grpc_files_file_proto_depIdxs,
		MessageInfos:      file_internal_grpc_files_file_proto_msgTypes,
	}.Build()
	File_internal_grpc_files_file_proto = out.File
	file_internal_grpc_files_file_proto_rawDesc = nil
	file_internal_grpc_files_file_proto_goTypes = nil
	file_internal_grpc_files_file_proto_depIdxs = nil
}
